### ISSUE TITLE
clearLines not working

### ISSUE THREAD

**Issue by coryb** [gosuri/uilive#11]
Hi Greg,

I was playing with `uilive` and am having troubles, not sure if it is my terminal or somethings else is wrong, perhaps you have an idea.

Basically when I run `go run ./example/main.go` I end up with:
```
$ go run ./example/main.go
Finished: Downloaded 100GB50) GB
```
So the previous output is not actually getting cleared, despite the `\033[2K` CSI code being printed and I still see the `50) GB` from the "Downloading" prints.

Oddly the `\033[J` code (clear to end of screen)  seems to work, so when I change clearLines to look like this it works fine:
```
func (w *Writer) clearLines() {
    fmt.Fprint(w.Out, strings.Repeat("\033[A", w.lineCount), "\033[J")
}
```

I am running on OSX Sierra, but I tried in iterm2 and terminal both with and without tmux and I get the same results with the original code.

Any ideas?  Thanks!
-Cory

**Comment by mbrlabs** [comment]
I can confirm this. I noticed it because one output was schorter than previous one and then they got mixed up. 

So this:
```go
fmt.Fprintln(writer, "aaa")
fmt.Fprintln(writer, "bb")
fmt.Fprintln(writer, "c")
```
becomes: ```cba ```

It seems like it just positions the cursor at the beginning of the line instead of clearing it.
I'm on Arch Linux + KDE. I tried different popular terminals but the problem stays.

Edit:
@coryb your solution fixed the problem for me as well

**Comment by mbrlabs** [comment]
Ok, so the real reason why this is not working is because the curser must be moved up before the line is cleared not after. 

@gosuri 
I just submitted a pull request, feel free to merge.

**Comment by mbrlabs** [comment]
I just got my hands on a Windows 10 machine, which seems to be affected by the exact same problem.

**Comment by ernoaapa** [comment]
Same here. Any change to merge the #12?

**Comment by asahasrabuddhe** [comment]
This might be late for you but I think this could be helpful for you or someone else who might stumble over this issue:

I have made a fork of this library and have managed to fix most of the issues. I would gladly do a PR here if @gosuri is interested in reviving this package. Until then, we could collaborate and keep this wonderful package alive right here: https://github.com/asahasrabuddhe/uilive
