### ISSUE TITLE
New goroutine

### ISSUE THREAD

**Issue by brianvoe** [gosuri/uilive#16]
How do you make this work with new go routines?

```
progressWrite := uilive.New()
progressWrite.Start()

for i := 0; i <= 100; i++ {
	go func() {
		fmt.Fprintf(progressWrite, "Downloading.. (%d/%d) GB\n", i, 100)
		time.Sleep(time.Millisecond * 20)
	}()
}
```

**Comment by brianvoe** [comment]
Any suggestion on this? Really need to figure out how i can use goroutines and still use uilive

**Comment by asahasrabuddhe** [comment]
Hi @brianvoe ,

Could you elaborate on what you are trying to achieve here? Why do you need 100 go routines to run a single progress bar?

https://github.com/gosuri/uiprogress

This library would be more suitable for you.

**Comment by brianvoe** [comment]
Would like have multiple progress bars going at once. Something like this.

============---> 75%
=====-------------> 25%
=============== 100%

Ill look out for your answer next year. haha jk

**Comment by asahasrabuddhe** [comment]
Perhaps this is what you need

https://github.com/gosuri/uiprogress
