### ISSUE TITLE
Event based flush of buffer

### ISSUE THREAD

**Issue by apoorvam** [gosuri/uilive#2]
Is it possible to expose some methods to add event based flushing of buffer, along with time based approach?

**Comment by gosuri** [comment]
[Writer.Flush](https://godoc.org/github.com/gosuri/uilive#Writer.Flush) will flush the buffer

**Comment by apoorvam** [comment]
Thank you for it. But im facing an issue when the text passed to writer is longer than console length. 
Here is a [gist](https://gist.github.com/apoorvam/bea7a0d0e7819a053d07) to reproduce it. 
This is same as the example, but just the string is longer than console length. 
Let me know if there is a way to get this working.

**Comment by gosuri** [comment]
The last line seems to be overwritten when width of the buffer exceeds screen width:

<img width="648" alt="screen shot 2015-12-08 at 11 11 19" src="https://cloud.githubusercontent.com/assets/70293/11665466/71c77c38-9d9c-11e5-9279-b9fc708db638.png">

Code:

``` go
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uilive"
)

func main() {
    writer := uilive.New()

    // start listening for updates and render
    writer.Start()

    str := ""
    for i := 0; i <= 100; i++ {
        str = str + "s"
    }
    str = str + "[end]"

    for i := 0; i <= 100; i++ {
        fmt.Fprintf(writer, "%d %s\n", i, str)
        time.Sleep(time.Second)
    }

    writer.Stop() // flush and stop rendering
}
```

Logging this as a separate issue
