### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by uded** [gosuri/uilive#20]
As stated - is anyone still maintaining this package? I see a lot of PRs and forks, but none of them seems to be a leading one...

**Comment by asahasrabuddhe** [comment]
This might be late for you but I think this could be helpful for you or someone else who might stumble over this issue:

I have made a fork of this library and have managed to fix most of the issues. I would gladly do a PR here if @gosuri is interested in reviving this package. Until then, we could collaborate and keep this wonderful package alive right here: https://github.com/asahasrabuddhe/uilive
