### ISSUE TITLE
Library should not call os.exit()

### ISSUE THREAD

**Issue by jasoncorbett** [gosuri/uilive#25]
With the latest commit if the tool fails to open /dev/tty (to get window size) then it calls os.exit().  A library should not call os.exit!  When my command line tool (that doesn't use this as a direct dependency) was run from an environment where there wasn't a tty it just exited.  No error, no problem.  I had to do an strace just to see that it was right after trying to open /dev/tty.

**Comment by jasoncorbett** [comment]
Better error handling in this case would be to assume a small window size, like 80x24

**Comment by asahasrabuddhe** [comment]
I think assuming a smaller size could cause other problems. However, I agree with not calling os.Exit(). We could as well return 0, 0

**Comment by devshorts** [comment]
just running into this as well, definitely should not call exit

**Comment by devshorts** [comment]
For what its worth I forked the uiprogress library and am using it https://github.com/devshorts/uiprogress. I removed the global progress handler that caused the os.exit on package init and exposed a util so you can gate your code paths on things like CICD without a tty
