### ISSUE TITLE
The last line is being overwritten when width of the buffer exceeds screen width

### ISSUE THREAD

**Issue by gosuri** [gosuri/uilive#3]
The last line seems to be overwritten when width of the buffer exceeds screen width:

<img width="648" alt="screen shot 2015-12-08 at 11 11 19" src="https://cloud.githubusercontent.com/assets/70293/11665466/71c77c38-9d9c-11e5-9279-b9fc708db638.png">

Code:

``` go
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uilive"
)

func main() {
    writer := uilive.New()

    // start listening for updates and render
    writer.Start()

    str := ""
    for i := 0; i <= 100; i++ {
        str = str + "s"
    }
    str = str + "[end]"

    for i := 0; i <= 100; i++ {
        fmt.Fprintf(writer, "%d %s\n", i, str)
        time.Sleep(time.Second)
    }

    writer.Stop() // flush and stop rendering
}
```

(Ref #2)

**Comment by apoorvam** [comment]
This [commit](https://github.com/apoorvam/uilive/commit/5d0824a0b9d46c1bb2ce9530053039203ae8059e) on my fork works for windows too. It has a dependency on `github.com/nsf/termbox-go`. 

Example code which works with this forked package:

```
package main

import (
    "fmt"
    "time"

    "github.com/apoorva/uilive"
)

func main() {
    writer := uilive.New()

    // start listening for updates and render
    writer.Start()
    uilive.InitializeTerminalWidth()

    str := ""
    for i:=0; i<200; i++ {
        str += "s"
    }

    str += "[end]"

    for i := 0; i <= 100; i++ {
        fmt.Fprintf(writer, "%d %s\n", i, str)
        time.Sleep(time.Second)
    }

    fmt.Fprintln(writer, "Finished: Downloaded 100GB")
    writer.Stop() // flush and stop rendering
}

```

**Comment by asahasrabuddhe** [comment]
This might be late for you but I think this could be helpful for you or someone else who might stumble over this issue:

I have made a fork of this library and have managed to fix most of the issues. I would gladly do a PR here if @gosuri is interested in reviving this package. Until then, we could collaborate and keep this wonderful package alive right here: https://github.com/asahasrabuddhe/uilive
