### ISSUE TITLE
glitch when the writer RefreshInterval is too little

### ISSUE THREAD

**Issue by renannprado** [gosuri/uilive#9]
When the RefreshInterval is too little like `time.Nanosecond` little or `0`, you should use `writer.Wait()` to be able to use the library, but still the text glitches a little. And when you do not use the `writer.Wait()`, the library isn't able to replace the text and start to act almost like a regular `fmt.Println`.

```go
package main

import (
        "fmt"

        "github.com/gosuri/uilive"
)

func main() {
        writer := uilive.New()

        // start listening for updates and render
        writer.RefreshInterval = 0

        writer.Start()

        for _, f := range []string{"Foo.zip", "Bar.iso"} {
                for i := 0; i <= 5000000; i++ {
                        fmt.Fprintf(writer, "Downloading %s.. (%d/%d) GB\n", f, i, 50)
                        writer.Wait()
                }
                fmt.Fprintf(writer.Bypass(), "Downloaded %s\n", f)
        }

        fmt.Fprintln(writer, "Finished: Downloaded 100GB")
        writer.Stop() // flush and stop rendering
}
```

**Comment by emil-nasso** [comment]
I think i just had the same issue. The progressbar ends up just being written on separate lines. Check this for an example:

```golang
package main

import (
	"fmt"
	"testing"
	"time"

	"github.com/gosuri/uilive"
)

func TestNoDelay(t *testing.T) {
	writer := uilive.New()
	writer.Start()
	for i := 0; i <= 5; i++ {
		fmt.Fprintf(writer, "(%d/%d)\n", i, 5)
	}
	writer.Stop()
}

func TestWithDelay(t *testing.T) {
	writer := uilive.New()
	writer.Start()
	for i := 0; i <= 5; i++ {
		fmt.Fprintf(writer, "(%d/%d)\n", i, 5)
		time.Sleep(time.Millisecond * 5)
	}
	writer.Stop()
}
```

The first test writes everything on it's own line.

This is the output:

```bash
$ go test
(0/5)
(1/5)
(2/5)
(3/5)
(4/5)
(5/5)
(5/5)
PASS
ok      github.com/emil-nasso/uilive-example    0.058s

```

**Comment by asahasrabuddhe** [comment]
This might be late for you but I think this could be helpful for you or someone else who might stumble over this issue:

I have made a fork of this library and have managed to fix most of the issues. I would gladly do a PR here if @gosuri is interested in reviving this package. Until then, we could collaborate and keep this wonderful package alive right here: https://github.com/asahasrabuddhe/uilive
